name: Android Release

on:
  push:
    branches:
      - 'master'
      - 'continuous-integration'
      - 'cross-platform'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'master'
    - 'continuous-integration'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.4.2
  ARTIFACT:     planets-qml.apk

jobs:
  build:
    runs-on:  ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==2.1.*
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       android
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt3d
              
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run:  |
              qmake -r ${{ env.SOURCE_DIR }}/planets-qml.pro
              make -j$(nproc)
              make -j$(nproc) apk_install_target 
      
      - name: Deploy
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
              ${{ runner.temp }}/Qt/5.15.2/android/bin/androiddeployqt --input ${{ env.SOURCE_DIR }}/build/android-planets-qml-deployment-settings.json --output ${{ env.SOURCE_DIR }}/build/android-build
      
      - name: Android artefact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR }}/build/${{ env.ARTIFACT }}

              
